"""Rename max_wind_gust to wind_speed in daily_summaries

Revision ID: 5d6fe28d9118
Revises: 6a6dcfac92c4
Create Date: 2026-01-07 20:04:50.413518+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6fe28d9118'
down_revision: Union[str, None] = '6a6dcfac92c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new wind_speed column
    op.add_column('daily_summaries', sa.Column('wind_speed', sa.Float(), nullable=True, comment='Mean wind speed in m/s over 24-hour period (average of available readings)'))

    # CRITICAL: Copy data from max_wind_gust to wind_speed before dropping
    op.execute('UPDATE daily_summaries SET wind_speed = max_wind_gust WHERE max_wind_gust IS NOT NULL')

    # Now safe to drop the old column
    op.drop_column('daily_summaries', 'max_wind_gust')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the old column
    op.add_column('daily_summaries', sa.Column('max_wind_gust', sa.FLOAT(), nullable=True))

    # CRITICAL: Copy data from wind_speed back to max_wind_gust before dropping
    op.execute('UPDATE daily_summaries SET max_wind_gust = wind_speed WHERE wind_speed IS NOT NULL')

    # Now safe to drop the wind_speed column
    op.drop_column('daily_summaries', 'wind_speed')
    # ### end Alembic commands ###
