"""initial schema

Revision ID: a632f91e0eb9
Revises: 
Create Date: 2026-01-04 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a632f91e0eb9"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # add other tables here...
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("stations")
    # drop other tables here...
    # ### end Alembic commands ###
