"""initial schema

Revision ID: a632f91e0eb9
Revises: 
Create Date: 2026-01-04 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a632f91e0eb9"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # Create stations table (with idempotent guard)
    # This migration may run alongside acb5aa092b78, so check if table exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    if 'stations' not in inspector.get_table_names():
        op.create_table(
            "stations",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=False),
            sa.Column("region", sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
    # Note: Other tables would be added here in original migration

def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_table("stations")
    # drop other tables here...
    # ### end Alembic commands ###
