"""Add sunshine_hours to daily_summaries

Revision ID: bd8ec41a4d68
Revises: 5d6fe28d9118
Create Date: 2026-01-07 21:00:32.923148+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8ec41a4d68'
down_revision: Union[str, None] = '5d6fe28d9118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_summaries', sa.Column('sunshine_hours', sa.Float(), nullable=True, comment='Total sunshine duration in hours during the 24-hour period'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_summaries', 'sunshine_hours')
    # ### end Alembic commands ###
